// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARFP8dwDN1Vsf0j-0P1ljt3lSVihsHtow',
    appId: '1:185909605227:web:dc26bbf5f6e15da06f522e',
    messagingSenderId: '185909605227',
    projectId: 'warshaout',
    authDomain: 'warshaout.firebaseapp.com',
    databaseURL: 'https://warshaout-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warshaout.appspot.com',
    measurementId: 'G-H5PWMPSQXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiP7M8CYHgTIPPrunBHhHik7usLcoBsWs',
    appId: '1:185909605227:android:0ab10ec9c70ab8386f522e',
    messagingSenderId: '185909605227',
    projectId: 'warshaout',
    databaseURL: 'https://warshaout-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warshaout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKChmAxVTwpXjq9JfukYUAvvxz4WWwC0',
    appId: '1:185909605227:ios:c9187ebfbd637b056f522e',
    messagingSenderId: '185909605227',
    projectId: 'warshaout',
    databaseURL: 'https://warshaout-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warshaout.appspot.com',
    androidClientId: '185909605227-62gpmdg1l3266k2dc768mtga8tuf0cog.apps.googleusercontent.com',
    iosClientId: '185909605227-hl2gs45unbasbkoqis5ph153jqr9ab3e.apps.googleusercontent.com',
    iosBundleId: 'com.warshaout.warshaout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKChmAxVTwpXjq9JfukYUAvvxz4WWwC0',
    appId: '1:185909605227:ios:c9187ebfbd637b056f522e',
    messagingSenderId: '185909605227',
    projectId: 'warshaout',
    databaseURL: 'https://warshaout-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warshaout.appspot.com',
    androidClientId: '185909605227-62gpmdg1l3266k2dc768mtga8tuf0cog.apps.googleusercontent.com',
    iosClientId: '185909605227-hl2gs45unbasbkoqis5ph153jqr9ab3e.apps.googleusercontent.com',
    iosBundleId: 'com.warshaout.warshaout',
  );
}
